name: exam_demo_unsplash
description: "A new Flutter project."



version: 1.0.2+3


environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  logger: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.0
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.0.11
  dio: ^5.4.1
  share_plus: ^7.2.2
  http_interceptor: ^2.0.0-beta.8
  get: ^4.6.6

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/animations/
